language: node_js
sudo: false
notifications:
  email: false
node_js:
  - stable
branches:
  only:
    - master
script: npm test
compiler: clang-3.6
env:
  global:
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
    - CC="clang"
    - CXX="clang++"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev
