language: node_js
node_js:
  - stable
branches:
  only:
    - master
sudo: false
script: npm test
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - CXX=g++-4.8
