language: node_js
sudo: false
notifications:
  email: false
node_js:
  - stable
branches:
  only:
    - master
script: npm test
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
